sudo: required
services:
  - docker

#build image to run tests
before_install:
  - docker build -t bgatty/react-test -f ./client/Dockerfile.dev ./client

#run tests 
script:
  - docker run bgatty/react-test npm test -- --coverage

# build production images
after_success:
  - docker build -t bgatty/multi-client ./client
  - docker build -t bgatty/multi-nginx ./nginx
  - docker build -t bgatty/multi-server ./server
  - docker build -t bgatty/multi-worker ./worker
#login to the docker cli using parameters defined in Travis repo setting
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push images to docker hub

  - docker push bgatty/multi-client
  - docker push bgatty/multi-nginx
  - docker push bgatty/multi-server
  - docker push bgatty/multi-worker

# deploy to AWS

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-756027542603
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY





